server:
  port: 8081
  servlet:
    context-path: /swear

swear:
  server-url: http://localhost:8080

logging:
  config: classpath:logback.xml

spring:
  mvc:
    view:
      prefix: /WEB-INF/view
      suffix: .html
    static-path-pattern: /static/**
  datasource-master:
    url: jdbc:mysql://localhost:3306/swallow_master?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
    db-name: dump_swear
    username: root
    password: yanni623..
    filters: wall,mergeStat
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  datasource-slave:
    url: jdbc:mysql://localhost:3306/swallow_master?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
    db-name: dump_swear
    username: root
    password: yanni623..
    filters: wall,mergeStat
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  datasource-default:
    url: jdbc:mysql://localhost:3306/swallow_master?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
    db-name: dump_swear
    username: root
    password: yanni623..
    filters: wall,mergeStat
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: cn.swallowff.modules.admin.modules.system.entity
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

