server:
  port: 8080

swear:
  muti-datasource:
    open: false
  kaptchaOpen: false
  spring-session-open: false

adminPath: /a
apiPath: /api

logging:
#  level:
#    root: info      #日志打印级别
  config: classpath:logback.xml

spring:
  profiles:
    active: single
  mvc:
    view:
      prefix: view
      suffix: .html
    static-path-pattern: /static/**

mybatis:
  type-aliases-package: cn.swallowff.modules.**.entity
  mapper-locations: classpath:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

---

spring:
  profiles: prod
  master-datasource:
    url: jdbc:mysql://120.79.225.48:3306/swallow_master?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
    db-name: swallow_master
    username: root
    password: yanni623..
    filters: wall,mergeStat
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  slave-datasource:
    url: jdbc:mysql://120.79.225.48:3306/swallow_slave?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
    db-name: swallow_slave
    username: root
    password: yanni623..
    filters: wall,mergeStat
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

---

spring:
  profiles: local
  master-datasource:
    url: jdbc:mysql://localhost:3306/swallow_master?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
    db-name: swallow_test
    username: root
    password: yanni623..
    filters: wall,mergeStat
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  slave-datasource:
    url: jdbc:mysql://localhost:3306/swallow_slave?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
    db-name: swallow_test2
    username: root
    password: yanni623..
    filters: wall,mergeStat
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

---

spring:
  profiles: single
  datasource:
    url: jdbc:mysql://120.79.225.48:3306/swallow_master?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
    db-name: swallow_master
    username: root
    password: yanni623..
    filters: wall,mergeStat
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

---